version: '3.8'
services:
  triton-voyager:
    build: .
    volumes:
      #- .:/voyager
      - .:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"

  triton-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/config:/models
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: ["tritonserver", "--model-repository=/models"]